install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;%QTDIR%\Tools\mingw530_32\binC:\MinGW\bin
build_script:
  - pwd
  - ls -l
  - cd OverwatchPlayerLog
  - ls -l
  - qmake OverwatchPlayerLog.pro
  - mingw32-make