language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=56
  - QT_BASE=57

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt561-trusty -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi

script:
  - qmake OverwatchPlayerLog/OverwatchPlayerLog.pro -r "CONFIG+=debug"
  - ls -l
  - make

notifications:
  email: false
