language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx

before_install: . Scripts/CI/$TRAVIS_OS_NAME/before_install.sh

install: . Scripts/CI/$TRAVIS_OS_NAME/install.sh

script: . Scripts/CI/$TRAVIS_OS_NAME/script.sh

notifications:
  email: false
